name: 3dev work
on: [push]

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "Some Text"
      - name: command in multitul
        run: |
          pwd
          ls -a  
     # - uses: actions/checkout@v4
      - name: copy
        run: |
          git init
          git remote add origin "https://@GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: done
        run: ls -a